[lint]
ignore = [
    # codebase (especially tests) is pretty inconsistent on formatting, maybe
    # re-enable that after having rationalized things
    "UP031",
    "UP032",
]

[lint.isort]
known-first-party = ["odoo"]