# -*- coding: utf-8 -*-
{
    'name': "runbot",
    'summary': "Runbot",
    'description': "Runbot for Odoo 17.0",
    'author': "Odoo SA",
    'website': "http://runbot.odoo.com",
    'category': 'Website',
    'version': '5.8',
    'application': True,
    'depends': ['base', 'base_automation', 'website'],
    'data': [
        'templates/dockerfile.xml',
        'data/dockerfile_data.xml',
        'data/build_parse.xml',
        'data/error_link.xml',
        'data/runbot_build_config_data.xml',
        'data/runbot_data.xml',
        'data/runbot_error_regex_data.xml',
        'data/website_data.xml',

        'security/runbot_security.xml',
        'security/ir.model.access.csv',
        'security/ir.rule.csv',

        'templates/utils.xml',
        'templates/badge.xml',
        'templates/batch.xml',
        'templates/branch.xml',
        'templates/build.xml',
        'templates/build_stats.xml',
        'templates/bundle.xml',
        'templates/commit.xml',
        'templates/dashboard.xml',
        'templates/frontend.xml',
        'templates/git.xml',
        'templates/nginx.xml',
        'templates/build_error.xml',
        'templates/new/page.xml',
        'templates/new/bundle.xml',
        'templates/new/batch.xml',
        'templates/new/build.xml',
        'templates/new/slot.xml',
        'templates/new/commit.xml',

        'views/branch_views.xml',
        'views/build_error_views.xml',
        'views/build_views.xml',
        'views/bundle_views.xml',
        'views/codeowner_views.xml',
        'views/commit_views.xml',
        'views/config_views.xml',
        'views/dashboard_views.xml',
        'views/dockerfile_views.xml',
        'views/error_log_views.xml',
        'views/host_views.xml',
        'views/repo_views.xml',
        'views/res_config_settings_views.xml',
        'views/stat_views.xml',
        'views/upgrade.xml',
        'views/warning_views.xml',
        'views/custom_trigger_wizard_views.xml',
        'wizards/stat_regex_wizard_views.xml',
        'views/menus.xml',
        'views/user.xml',
    ],
    'license': 'LGPL-3',

    'assets': {
        'web.assets_backend': [
            'runbot/static/src/libs/diff_match_patch/diff_match_patch.js',
            'runbot/static/src/js/fields/*',
        ],
        'runbot.assets_frontend': [
            ('include', 'web.assets_frontend_minimal'),

            'web/static/lib/luxon/luxon.js',
            'web/static/lib/owl/owl.js',
            'web/static/lib/owl/odoo_module.js',
            '/runbot/static/src/libs/jquery/jquery.js',
            'web/static/src/legacy/js/libs/jquery.js',
            '/runbot/static/src/libs/popper/popper.js',
            'web/static/src/legacy/js/core/class.js',

            'web/static/src/env.js',
            'web/static/src/core/**/*.js',  # Note that 'web/static/src/core/utils/ui.js' is included in assets_frontend_minimal already
            'web/static/src/core/**/*.xml',  # Note that 'web/static/src/core/utils/ui.js' is included in assets_frontend_minimal already
            'web/static/src/public/public_component_service.js',
            'web/static/src/legacy/js/public/public_root.js',
            'web/static/src/legacy/js/public/public_root_instance.js',
            'web/static/src/legacy/js/public/public_widget.js',
            'web/static/src/legacy/js/public/signin.js',

            '/runbot/static/src/libs/bootstrap/css/bootstrap.css',
            '/runbot/static/src/libs/fontawesome/css/font-awesome.css',
            '/runbot/static/src/css/runbot.scss',
            '/runbot/static/src/css/legacy.scss',
            '/runbot/static/src/css/dark.scss',
            '/runbot/static/src/css/red404.scss',

            '/runbot/static/src/libs/bootstrap/js/bootstrap.bundle.js',
            '/runbot/static/src/js/runbot.js',
            '/runbot/static/src/js/manage_preferences_dialog.js',
            '/runbot/static/src/js/manage_preferences_dialog.xml',
        ],
    },
    'post_load': 'runbot_post_load',
}
